name: CI Pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest

    env:
      DAGS_HUB_TOKEN : ${{secrets.DAGS_HUB_TOKEN}}
      DAGSHUB_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
      AWS_ACCESS_KEY_ID : ${{secrets.AWS_ACCESS_KEY}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.REGION}}

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt

      - name: Configure AWS credentials (for boto3 & DVC)
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set default.region $AWS_DEFAULT_REGION

      - name: Authenticate with DagsHub (Git + MLflow + DVC)
        run: |
          git config --global user.email "ci-bot@github.com"
          git config --global user.name "GitHub Actions"
          git config --global credential.helper store
          git remote set-url origin https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Mlops_practice.git
          echo "https://${{ secrets.DAGSHUB_USERNAME }}:${{ secrets.DAGS_HUB_TOKEN }}@dagshub.com" > ~/.git-credentials

          echo "MLFLOW_TRACKING_USERNAME=${{ secrets.DAGSHUB_USERNAME }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_PASSWORD=${{ secrets.DAGS_HUB_TOKEN }}" >> $GITHUB_ENV
          echo "MLFLOW_TRACKING_URI=https://dagshub.com/${{ secrets.DAGSHUB_USERNAME }}/Mlops_practice.mlflow" >> $GITHUB_ENV

          dvc remote modify origin --local auth basic
          dvc remote modify origin --local user ${{ secrets.DAGSHUB_USERNAME }}
          dvc remote modify origin --local password ${{ secrets.DAGS_HUB_TOKEN }}



      - name: run pipeline
        env:
          DAGS_HUB_TOKEN: ${{secrets.DAGS_HUB_TOKEN }}
        run: |
          dvc repro

      - name: Run model tests
        env:
          DAGS_HUB_TOKEN: ${{ secrets.DAGS_HUB_TOKEN }}
        run: |
          python -m unittest tests/test_model.py

      - name: Promote model to production
        if: success()
        env:
          DAGS_HUB_TOKEN: ${{ secrets.DAGS_HUB_TOKEN}}
        run: python scripts/promote_model.py

      - name: Run Flask app tests
        if: success()
        env:
          DAGS_HUB_TOKEN: ${{ secrets.DAGS_HUB_TOKEN }}
        run: python -m unittest tests/test_flask_app.py

      - name: Login to AWS ECR
        if: success()
        run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_KEY }}
            aws configure set region ${{ secrets.REGION }}
            aws ecr get-login-password --region ${{ secrets.REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

